name: portfolio
description: Portfolio.
version: 1.1.1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  animated_text_kit: ^4.2.2
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  go_router: ^14.1.2
  icons_plus: ^5.0.0
  intl: ^0.18.1
  provider: ^6.1.2
  responsive_builder: ^0.7.0
  shared_preferences: ^2.2.3
  url_launcher: ^6.2.6
  web: ^0.5.1

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/images/
    - assets/files/

  fonts:
    - family: PixelifySans
      fonts:
        - asset: assets/fonts/PixelifySans-Regular.ttf

    - family: SpaceGrotesk
      fonts:
        - asset: assets/fonts/SpaceGrotesk-Regular.ttf
